name: 📚 Deploy Documentation

env:
  DOCS_CNAME: "starlight-theme.entapp.northwestern.edu"
  NODE_VERSION: "24"
  PNPM_VERSION: "10.x.x"

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "packages/**"
  workflow_dispatch:

concurrency:
  group: deploy-docs-${{ github.ref }}

jobs:
  deploy:
    name: 🌐 Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build docs
        run: pnpm docs:build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.repository == 'NIT-Administrative-Systems/northwestern-starlight-theme'
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/dist
          cname: ${{ env.DOCS_CNAME }}
